# Generated by Django 5.1.14 on 2025-11-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_threshold', models.IntegerField(default=75, help_text='Batas minimum kemiripan untuk dianggap plagiat (0-100)')),
                ('auto_delete_days', models.IntegerField(default=30, help_text='Hapus otomatis laporan setelah N hari (0 = tidak otomatis hapus)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Plagiarisme',
                'verbose_name_plural': 'Pengaturan Plagiarisme',
                'db_table': 'plagiarism_settings',
            },
        ),
    ]
