# Generated by Django 5.2.8 on 2025-11-27 11:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('similarity_score', models.IntegerField(blank=True, help_text='Skor plagiarisme global (0-100)', null=True)),
                ('similarity_local', models.IntegerField(blank=True, help_text='Skor dari repository lokal', null=True)),
                ('similarity_internet', models.IntegerField(blank=True, help_text='Skor dari internet', null=True)),
                ('matched_sources', models.TextField(blank=True, help_text='Detail sumber yang cocok (JSON string)', null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('check_date', models.DateTimeField(auto_now_add=True)),
                ('source_mode', models.CharField(choices=[('local', 'Lokal'), ('internet', 'Internet'), ('both', 'Keduanya')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('processing', 'Sedang Diproses'), ('completed', 'Selesai'), ('failed', 'Gagal')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file_deleted', models.BooleanField(default=False)),
                ('file_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file_deleted_reason', models.CharField(blank=True, default='Auto-cleanup policy', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histori Pemeriksaan',
                'verbose_name_plural': 'Histori Pemeriksaan',
                'db_table': 'plagiarism_history',
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='UserUploadQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('upload_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kuota Upload User',
                'verbose_name_plural': 'Kuota Upload User',
                'db_table': 'user_upload_quota',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
