# Generated by Django 5.1.14 on 2025-11-27 03:51

import apps.repository.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('basename', models.CharField(blank=True, max_length=255)),
                ('filetype', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to=apps.repository.models.get_upload_path)),
                ('extracted_text_path', models.CharField(blank=True, max_length=500, null=True)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('extracted_text_length', models.IntegerField(default=0)),
                ('index_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Indexing'), ('indexed', 'Indexed'), ('failed', 'Indexing Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'repository_files',
            },
        ),
    ]
